Обновление века (часть 1)
htmlacademy-ecmascript/1963109-big-trip-17 pull request #11
Opened 2022-06-08 19:41 UTC by Laskoviy

как реализовать в editPointView.js правильную отрисовку доступных офферов(необходимо связать типы офферов и поинтов, там уже есть закоменченый код для этого(строки 55-71)(вставить нужно по идее в отдельный темплейт на строках 22-40), но я не понимаю как его применить правильно) типы офферов и поинтов нужно связать чтобы не было путаницы, например, если поинт отель, а оффер к нему выбрать радио станцию. По идее радио станция это такси)

---
:mortar_board: [Обновление века (часть 1)](https://up.htmlacademy.ru/ecmascript/17/user/1963109/tasks/12)

:boom: https://htmlacademy-ecmascript.github.io/1963109-big-trip-17/11/

2022-06-09 09:24 UTC, Elsee commented on src/const.js
> +const OFFERS = ['Add luggage', 'Switch to comfort', 'Add meal', 'Choose seats', 'Travel by train'];
Давай начнём с того, что с массивом OFFERS не так всё просто. Для этого обратимся к ТЗ, чтобы понять, что из себя вообще представляют офферы. Видим пункт 1.8.1 "Ресурсы": https://up.htmlacademy.ru/ecmascript/17/project/big-trip#resource .
Разбираемся: 
1) Видим пункт **"Общий список дополнительных предложений /offers"**, понимаем, что список офферов нам будет приходить с сервера по эндпоинту `/offers`, в body которого нам будет приходить _"массив из элементов вида `OffersByType`"_
2) Разбираемся, что из себя представляет `OffersByType`. Видим в ТЗ:
OffersByType:
```
{
  "type": "taxi",
  "offers": $Array<$Offer>
}
```

OffersByType.type — одно из следующих значений:
```
["taxi", "bus", "train", "ship", "drive", "flight", "check-in", "sightseeing", "restaurant"]
```

3) Т.к. видим, что в поле offers нам будет приходить массив  из элементов вида `Offer`, идём разбираться, что такое `Offer`:
Offer:
```
{
  "id": 1,
  "title": "Upgrade to a business class",
  "price": 120
}
```


**Собираем всё вместе**
Т.к. доступные предложения будут приходить к нам с сервера, я бы порекоммендовала их хранить всё-таки в папке mocks, а не constants. Дальше собираем структуру предложений. Выглядеть это должно как-то так:

Offers:

```
[
  {
    type: "taxi",
    offers: [
      {
        id: 1,
        title: "Upgrade to a business class",
        price: 120
      },
      {
        id: 2,
        title: "Order Uber",
        price: 20
      },
      ...
    ]
  },
  {
    type: "bus",
    offers: [] //предположим, что нет для точки доп.предложений
  },
  ...
  {
    type: "flight",
    offers: [
      {
        id: 1,
        title: "Add luggage",
        price: 50
      },
      {
        id: 2,
        title: "Switch to comfort",
        price: 80
      },
      {
        id: 3,
        title: "Add meal",
        price: 15
      },
      {
        id: 4,
        title: "Choose seats",
        price: 5
      },
      {
        id: 5,
        title: "Travel by train",
        price: 40
      }
    ]
  },
  ...
]
```

В общем, для каждого типа точки свой набор дополнительных услуг


**Как нам это всё соединить с формой редактирования**
1) В форме редактирования у нас для каждой точки есть селект с типом точки (вот он на скриншоте):
http://joxi.ru/4AkNzpFodvlR2q
![image](https://user-images.githubusercontent.com/7502553/172810212-c7be7c5c-afbd-460c-9926-2606d17185be.png)

Он хранится в поле `type` точки
2) По выбранному типу точки, подтягиваем из моков нужный набор офферов (предположим, он у нас называется `availableOffers`):
```
const {offers} = availableOffers.find((offer) => offer.type === selectedType); // selectedType здесь - это выбранный в текущий момент тип путешествия (["taxi", "bus", "train", "ship", "drive", "flight", "check-in", "sightseeing", "restaurant"])
```

Ну и всё, выводишь свой набор предложений в соответствующую разметку:
```
offers.map((offer) => (
 `<input class="event__offer-checkbox visually-hidden" id="event-offer-${offer.id}" type="checkbox" name="event-offer-${offer.id}" checked="">
...`
))
```

2022-06-13 08:49 UTC, Elsee commented on src/mock/structures.js
> +export const serverOffers = [
ну это не serverOffers, это mockOffers )

2022-06-13 08:49 UTC, Elsee commented on src/mock/structures.js
> +  return new Array(count).fill('').map(() => getRandomInteger(0, 5));
ну тут может возникнуть ситуация, когда индексы повторяются ) Но в целом это не страшно, конечно

2022-06-13 11:45 UTC, Elsee commented on src/view/editPointView.js
> +  const resultOffers = availableOffers.offers.filter((offer) => offers.find((id) => id === offer.id)); // Офферы отфильтрованные по id
тут было бы правильнее назвать `selectedOffers` - выбранные пользователем предложения. Как думаешь?

2022-06-13 11:45 UTC, Elsee commented on src/view/editPointView.js
> +      ${createEditOfferTemplate(resultOffers)}
ну вот в эту функцию тебе надо передавать и все доступные дополнительные опции для типа точки (чтобы было из чего выбирать, правильно?) и уже выбранные пользователем опции (закрасим их синеньким, чтобы показать, что они уже выбраны)

2022-06-13 11:45 UTC, Elsee commented on src/view/editPointView.js
> +        <input class="event__offer-checkbox  visually-hidden" id="event-offer-${offer.id}" type="checkbox" name="event-offer-${offer.id}" checked="">
ну они же не все должны быть `checked`, правильно? Только выбранные.
```
const createEditOfferTemplate = (offers, selectedOffers) => {
...
<input 
  class="event__offer-checkbox visually-hidden" 
  id="event-offer-${offer.id}" 
  type="checkbox" 
  name="event-offer-${offer.id}" 
  ${selectedOffers.includes(offer.id) ? 'checked' : ''}
>

2022-06-13 11:45 UTC, Elsee commented on src/view/editPointView.js
> +          <label class="event__offer-label" for="event-offer-luggage-1">
не забывай в for прописать корректный id

2022-06-16 08:09 UTC, Elsee commented on src/const.js
> +  type: ''
ну вот, кажется, что как раз тип по умолчанию тебе нужен, чтобы сразу и доп.опции подтянуть и описание, если такие есть

2022-06-18 16:27 UTC, Laskoviy commented
Не понимаю как правильно сделать 6 задание. Нужно ли передавать кроме поинта ещё какие то значения в форму редактирования и создания поинта?? У меня вроде получилось настроить типы но проблема с отображением офферов по типу и сохранением формы и тд.....

2022-06-19 09:38 UTC, Elsee reviewed
> _"проблемы с сохранением формы"._ Ты уже умеешь обновлять данные точки, в предыдущем задании делали (добавляли в избранное). Ты эту логику чуть-чуть поломал, кстати, надо поправить: в `boardPresenter.js` в методе `#handlePointChange` нужно на 61-ой строчке нужно заменить `this.#pointPresenter.get(updatedPoint.point.id).init(updatedPoint);` на `this.#pointPresenter.get(updatedPoint.id).init(updatedPoint);`

Используй свои предыдущие наработки. Только теперь надо будет не только поле `isFavorite` обновлять, но и все, которые нужны: деструктурируем предыдущие значени и объединяем с новыми 
```
#handleFormSubmit = (point) => {//метод для обновления задачи через кнопку save
    this.#changeData({...this.#point, ...point});
    this.#replaceFormToPoint();
  };
```

2022-06-19 09:38 UTC, Elsee commented on src/view/editPointView.js
> +  const availableOffers = mockOffers.find((offer) => offer.type === type); // Доступные офферы по типу поинта
ну раз ввёл состояние `checkedType`, от него и отталкивайся. Ты же в `updateElement` меняешь именно checkedType, а не type:
```
const availableOffers = mockOffers.find((offer) => offer.type === checkedType);
```

2022-06-21 07:51 UTC, Elsee commented on src/view/editPointView.js
> +  const selectedOffers = availableOffers.offers.filter((offer) => offers.find((Offerid) => Offerid === offer.id)); // Офферы отфильтрованные по id
с большой буквы называем только классы и перечисления. Тут ни класс, ни перечисление, обычный параметр функции, некорректное именование

2022-06-22 09:41 UTC, Elsee requested changes

2022-06-22 09:41 UTC, Elsee commented on src/view/editPointView.js
> +    this.element.querySelector('.event__input--destination').addEventListener('focus', this.#focusDestinationHandler);
вот это убери, очень недружественное для пользователя поведение, когда поле очищается на фокус.

2022-06-22 09:41 UTC, Elsee commented on src/view/editPointView.js
> +</form>
с фотографиями секцию потерял:
```
<div class="event__photos-container">
...
```

Сразу после `<p class="event__destination-description">` она должна идти, когда есть фотки

2022-06-22 09:41 UTC, Elsee commented on src/view/editPointView.js
> +  const selectedOffers = availableOffers.offers.filter((offer) => offers.find((offerid) => offerid === offer.id)); // Офферы отфильтрованные по id
Что тут происходит? И почему у тебя при смене типа все доп.опции выделены по умолчанию? Так не долен себя компонент вести: выбранными долэны быть только те доп.опции, которые **пользователь выберет**

2022-06-22 09:41 UTC, Elsee commented on src/view/editPointView.js
> +  #changeTypeHandler = (evt) => {
У тебя сейчас на смену типа в форме изменения применяются и к точке сразу, без сохранения. Тип точки должен меняться только по клику на кнопку Save

2022-06-22 09:41 UTC, Elsee commented on src/view/addNewPointView.js
> +import { BLANK_POINT } from '../const.js';
форма не рабочая

2022-06-22 10:54 UTC, Laskoviy commented on src/view/editPointView.js
> +  const selectedOffers = availableOffers.offers.filter((offer) => offers.find((offerid) => offerid === offer.id)); // Офферы отфильтрованные по id
ну я же оставил комментарии что тут отсортировываются два типа офферов которые по типу и которые по id

2022-06-22 20:10 UTC, merged